# Render Blueprint: https://render.com/docs/blueprint-spec
services:
  - type: web
    name: wordle-ipro
    runtime: docker
    plan: free
    region: frankfurt
    dockerfilePath: ./Dockerfile
    dockerContext: .
    healthCheckPath: /
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: ConnectionStrings__WordleDb
        value: Data Source=/app/data/wordle.db
